"""
argus/schemas/signals.py

Canonical Pydantic data contracts for the ARGUS multi-agent system.

Responsibilities:
  - Define all typed schema classes used for inter-agent signal propagation
  - Enforce field-level validation constraints (conviction caps, weight bounds)
  - Provide cross-model validators that prevent silent allocation bugs

Not responsible for:
  - Signal computation (see individual agent modules)
  - Serialization format (handled by Pydantic model_dump_json)

Dependencies:
  - pydantic >= 2.0
"""

from __future__ import annotations

import math
import uuid
import warnings
from collections import Counter
from datetime import date, datetime
from enum import Enum
from typing import Annotated, Literal

from pydantic import (
    BaseModel,
    BeforeValidator,
    Field,
    computed_field,
    field_validator,
    model_validator,
)

from argus.params import PORTFOLIO, SYSTEM
from argus.schemas.prompting import PromptText


class Signal(str, Enum):
    """Market direction classification returned by an analyst agent."""

    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


class Regime(str, Enum):
    """Economic regime state classification generated by the Macro agent."""

    EXPANSION = "EXPANSION"
    CONTRACTION = "CONTRACTION"
    TRANSITIONAL = "TRANSITIONAL"


class RiskVerdict(str, Enum):
    """Risk assessment outcome determining portfolio allocation routing."""

    APPROVE = "APPROVE"   # proceed with proposed_weight unchanged
    VETO = "VETO"         # block the position entirely
    REDUCE = "REDUCE"     # approved_weight < proposed_weight


class VixRegime(str, Enum):
    """Categorized volatility regimes derived from the CBOE VIX spot level."""

    LOW = "LOW"           # VIX < 15
    MEDIUM = "MEDIUM"     # 15 ≤ VIX < 25
    HIGH = "HIGH"         # 25 ≤ VIX < 35
    EXTREME = "EXTREME"   # VIX ≥ 35 → Governor kill-switch zone


class YieldCurve(str, Enum):
    """Yield curve classification based on the US Treasury 10Y-2Y spread."""

    NORMAL = "NORMAL"     # spread > +25 bps
    FLAT = "FLAT"         # -25 bps ≤ spread ≤ +25 bps
    INVERTED = "INVERTED"  # spread < -25 bps (recession signal)


class SectorSignal(str, Enum):
    """Macroeconomic-implied equity sector preferences."""

    GROWTH_FAVORED = "GROWTH_FAVORED"  # risk-on, lower rates
    VALUE_FAVORED = "VALUE_FAVORED"    # rising rates, reflation
    DEFENSIVE = "DEFENSIVE"            # high VIX / contraction regime


SESSION_STATE_REQUIRED_KEYS: frozenset[str] = frozenset({
    "rsi_14",
    "macd_histogram",
    "bb_percent_b",
    "adx_14",
    "vwap_distance",
    "volume_ratio",
    "atr_pct",
    "momentum_30m",
    "momentum_1d",
    "close",
    "timestamp",
})

# timestamp is a required key but not a numeric indicator — it's checked for
# presence like every other key, but exempt from the finite-float check
# below, which would otherwise raise trying to float() an ISO string.
_NUMERIC_SESSION_STATE_KEYS = SESSION_STATE_REQUIRED_KEYS - {"timestamp"}


def missing_session_state_keys(state: dict) -> list[str]:
    """Finds required session-state keys that are absent, None, or non-finite.

    The contract a compressed technical feature dict must satisfy before a
    consumer can trust it: data/pipeline.py's compress_all() uses this to
    decide what "ready" means, and agents/technical.py's analyze() uses it
    to decide what "usable" means, so both share one definition instead of
    each re-deriving it.

    Args:
        state: A compressed technical feature dict.

    Returns:
        Sorted list of missing/invalid key names; empty if the state is
        complete.
    """
    missing = [k for k in SESSION_STATE_REQUIRED_KEYS if state.get(k) is None]
    if missing:
        return sorted(missing)
    return sorted(
        k for k in _NUMERIC_SESSION_STATE_KEYS if not math.isfinite(float(state[k]))
    )


_CONVICTION_MAX = 0.95


def _clamp_conviction(v: float) -> float:
    """Clamps a conviction value to 0.95, warning when truncation occurs.

    The 0.95 ceiling prevents the system from expressing certainty in any signal,
    preserving a minimum margin of doubt as a risk management mechanism.

    Args:
        v: Raw conviction value.

    Returns:
        Clamped value ≤ 0.95.
    """
    if v > _CONVICTION_MAX:
        warnings.warn(
            f"conviction={v:.4f} exceeds maximum {_CONVICTION_MAX}; "
            "clamping to 0.95 — check your scoring function.",
            stacklevel=3,
        )
        return _CONVICTION_MAX
    return v


# BeforeValidator is listed after the constraints so it wraps them: the clamp
# runs first and the ge/le check sees the clamped value. Reversing the order
# would make a conviction of 0.99 a ValidationError instead of a warning.
_Conviction = Annotated[
    float,
    Field(ge=0.0, le=_CONVICTION_MAX),
    BeforeValidator(_clamp_conviction),
]


class MacroContext(BaseModel):
    """Macroeconomic state and conviction multipliers for specialist agents."""

    fed_funds: float = Field(..., description="Effective Federal Funds Rate (%)")
    cpi_yoy: float = Field(..., description="Consumer Price Index YoY (%)")
    unemployment: float = Field(..., description="Unemployment Rate (%)")
    t10y2y: float = Field(..., description="10-Year minus 2-Year Treasury spread (%)")
    consumer_sentiment: float = Field(..., description="UMich Consumer Sentiment Index")
    vix_level: float = Field(..., ge=0.0, description="CBOE VIX spot level")

    macro_regime: Regime = Field(..., description="HMM-detected economic regime")
    regime_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="HMM posterior probability for the detected regime",
    )
    model_healthy: bool = Field(
        ...,
        description=(
            "True when regime_confidence is a real HMM posterior; False when the "
            "classifier fell back to the fixed-confidence rule-based heuristic"
        ),
    )
    interest_rate_trend: Literal["RISING", "FALLING", "STABLE"] = Field(
        ..., description="Direction of short-term interest rates"
    )
    yield_curve_shape: YieldCurve = Field(..., description="10Y-2Y Treasury spread shape")
    vix_regime: VixRegime = Field(..., description="Categorical VIX bucket")
    vix_percentile: float = Field(
        ..., ge=0.0, le=100.0, description="VIX vs. trailing 252-day distribution"
    )
    inflation_trajectory: Literal["RISING", "FALLING", "STABLE"] = Field(
        ..., description="Direction of CPI year-over-year rate"
    )
    sector_rotation_signal: SectorSignal = Field(..., description="Macro-implied sector preference")
    agent_multipliers: dict[str, float] = Field(
        ...,
        description=(
            "Conviction multipliers keyed by agent name "
            "(fundamental, technical, sentiment). Range [0.5, 1.5]."
        ),
    )
    api_calls_used: int = Field(0, ge=0)
    timestamp: datetime = Field(..., description="Naive local timestamp of signal production")

    @field_validator("agent_multipliers", mode="before")
    @classmethod
    def validate_multiplier_keys(cls, v: dict[str, float]) -> dict[str, float]:
        """Ensures required agent keys exist, defaulting missing ones to 1.0.

        Args:
            v: Raw multiplier dict from the macro agent.

        Returns:
            Validated dict with at least fundamental, technical, and sentiment keys.

        Raises:
            ValueError: If any multiplier falls outside (0, 2].
        """
        required = {"fundamental", "technical", "sentiment"}
        for key in required:
            v.setdefault(key, 1.0)
        for key, mult in v.items():
            if not (0.0 < mult <= 2.0):
                raise ValueError(
                    f"agent_multipliers['{key}']={mult} is outside (0, 2]; "
                    "must be a positive scaling factor"
                )
        return v


class TechnicalSignal(BaseModel):
    """Technical indicator outputs and directional signals for one asset."""

    ticker: str = Field(..., description="Equity ticker symbol, e.g. 'AAPL'")

    current_price: float = Field(..., ge=0.0, description="Latest closing price")
    rsi_14: float = Field(..., ge=0.0, le=100.0, description="14-period RSI value [0, 100]")
    macd_histogram: float = Field(..., description="MACD histogram value")
    bb_percent_b: float = Field(..., description="Bollinger %B [0, 1] (>1 or <0 = breach)")
    atr_pct: float = Field(..., ge=0.0, description="ATR as % of price (volatility proxy)")
    adx_14: float = Field(..., ge=0.0, le=100.0, description="14-period ADX trend strength")
    vwap_distance: float = Field(..., description="(price - VWAP) / VWAP; signed")
    volume_ratio: float = Field(..., ge=0.0, description="Current volume / 20-day avg volume")
    momentum_30m: float = Field(..., description="30-minute log-return")
    momentum_1d: float = Field(..., description="1-day log-return")

    signal: Signal = Field(..., description="Directional label derived from net_score")
    conviction: _Conviction = Field(
        ..., description="Normalised confidence in the signal [0, 0.95]"
    )
    net_score: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description="Raw weighted composite score before discretisation",
    )

    api_calls_used: int = Field(0, ge=0, description="External API calls consumed")
    timestamp: datetime = Field(..., description="Naive local timestamp of signal production")


class FundamentalVerdict(BaseModel):
    """What the LLM returns for a fundamental analysis — judgement only.

    Never carries measured ratios: those come from the market-data provider
    and are merged in by the agent to build a FundamentalSignal. See
    GLOSSARY.md's Verdict entry.
    """

    signal: Annotated[Signal, PromptText("signal (string)")] = Field(
        ..., description="Directional label"
    )
    conviction: Annotated[_Conviction, PromptText("conviction (float 0.0–1.0)")]
    moat_score: Annotated[float, PromptText("moat_score (int 1–10)")] = Field(
        ..., ge=0.0, le=10.0, description="Qualitative competitive moat [0, 10]"
    )
    reasoning: Annotated[str, PromptText("reasoning (string ≤80 words, no markdown)")] = Field(
        ..., description="LLM-generated investment thesis"
    )


class FundamentalSignal(BaseModel):
    """Corporate fundamentals and qualitative moat rating for one asset."""

    ticker: str = Field(..., description="Equity ticker symbol")

    sector: str = Field(..., description="GICS Sector")
    industry: str = Field(..., description="GICS Industry")
    marketCap: float | None = Field(None, description="Market Capitalization (USD)")
    pe_ttm: float | None = Field(None, description="Trailing P/E ratio")
    p_fcf: float | None = Field(None, description="Price to Free Cash Flow")
    revenue_growth_yoy: float | None = Field(None, description="YoY revenue growth rate")
    operating_margin: float | None = Field(None, description="Operating income / revenue")
    net_margin: float | None = Field(None, description="Net income / revenue")
    fcf_yield: float | None = Field(None, description="Free cash flow / market cap")
    debt_to_equity: float | None = Field(None, ge=0.0, description="Total debt / equity")
    current_ratio: float | None = Field(None, description="Current assets / current liabilities")
    roe: float | None = Field(None, description="Return on equity")
    roic: float | None = Field(None, description="Return on invested capital")
    data_as_of_date: date = Field(..., description="Point-in-time date for financial data")

    signal: Signal = Field(..., description="Directional label")
    conviction: _Conviction
    moat_score: float = Field(
        ..., ge=0.0, le=10.0, description="Qualitative competitive moat [0, 10]"
    )
    reasoning: str = Field(
        ..., max_length=400, description="LLM-generated investment thesis (≤400 chars)"
    )

    api_calls_used: int = Field(1, ge=0)
    timestamp: datetime = Field(..., description="Naive local timestamp of signal production")


class SentimentVerdict(BaseModel):
    """What the LLM itself returns for a sentiment synthesis — judgement only.

    Never carries the FinBERT metrics: those are computed locally and merged
    in by the agent to build a SentimentSignal. See GLOSSARY.md's Verdict entry.
    """

    signal: Annotated[Signal, PromptText('"BULLISH|BEARISH|NEUTRAL"')] = Field(
        ..., description="Directional label"
    )
    conviction: Annotated[_Conviction, PromptText("<float 0.0–1.0>")]
    sentiment_decay_risk: Annotated[
        Literal["LOW", "MEDIUM", "HIGH"], PromptText('"LOW|MEDIUM|HIGH"')
    ] = Field(..., description="Estimated speed at which the sentiment signal will decay")
    reasoning: Annotated[str, PromptText('"<≤60 words citing the primary driver>"')] = Field(
        ..., description="LLM rationale for the signal"
    )


class SentimentSignal(BaseModel):
    """News sentiment features with associated signal conviction scores."""

    ticker: str = Field(..., description="Equity ticker symbol")

    finbert_net_score: float | None = Field(
        None,
        ge=-1.0,
        le=1.0,
        description="FinBERT weighted net score [-1, +1]; None if the news fetch failed",
    )
    pct_positive: float = Field(
        ..., ge=0.0, le=1.0, description="Fraction of articles scored positive"
    )
    pct_negative: float = Field(
        ..., ge=0.0, le=1.0, description="Fraction of articles scored negative"
    )
    news_volume_7d: int = Field(
        ..., ge=0, description="Total news articles ingested (7-day window)"
    )
    news_scored_count: int = Field(
        0,
        ge=0,
        description="Articles actually scored by FinBERT (<=25, after per-headline "
        "failures) — the denominator behind pct_positive/pct_negative. 0 for signals "
        "persisted before this field existed.",
    )
    news_data_available: bool = Field(
        True, description="False means the news fetch failed; news metrics are placeholders"
    )
    upcoming_catalyst: bool = Field(..., description="True if earnings / FDA / FOMC within 14 days")

    signal: Signal = Field(..., description="Directional label")
    conviction: _Conviction
    sentiment_decay_risk: Literal["LOW", "MEDIUM", "HIGH"] = Field(
        ..., description="Estimated speed at which the sentiment signal will decay"
    )
    reasoning: str = Field(
        ..., max_length=400, description="LLM rationale for the signal (≤400 chars)"
    )
    api_calls_used: int = Field(1, ge=0)
    timestamp: datetime = Field(..., description="Naive local timestamp of signal production")

    @model_validator(mode="after")
    def pct_sums_to_one_approx(self) -> SentimentSignal:
        """Warns (not errors) if pct_positive + pct_negative exceeds 1.0.

        A sum > 1 indicates a normalisation bug in the upstream FinBERT aggregation
        step. A warning is preferred over a hard error to avoid rejecting otherwise
        valid signals from borderline rounding artifacts.
        """
        total = self.pct_positive + self.pct_negative
        if total > 1.001:
            warnings.warn(
                f"pct_positive ({self.pct_positive:.3f}) + pct_negative "
                f"({self.pct_negative:.3f}) = {total:.3f} > 1.0 for ticker "
                f"{self.ticker!r}; check normalisation.",
                stacklevel=3,
            )
        return self


class RiskAssessment(BaseModel):
    """Risk verdict, exposure limits, and volatility stats for a position."""

    verdict: RiskVerdict = Field(..., description="Disposition on the proposed portfolio")
    approved_weight: float = Field(
        ..., ge=0.0, le=1.0, description="Equity exposure approved by Risk agent"
    )
    proposed_weight: float = Field(
        ..., ge=0.0, le=1.0, description="Aggregate equity exposure before risk review"
    )
    veto_reasons: list[str] = Field(
        default_factory=list, description="Human-readable reasons for VETO / REDUCE"
    )

    var_99: float | None = Field(None, description="99% 1-day Value-at-Risk (as + %)")
    cvar: float | None = Field(None, description="Conditional VaR / Expected Shortfall")
    marginal_var: float | None = Field(None, description="Marginal contribution to portfolio VaR")
    portfolio_beta: float | None = Field(None, description="Dollar-weighted beta vs SPY")
    avg_correlation: float | None = Field(
        None, ge=-1.0, le=1.0, description="Average pairwise return correlation"
    )

    stop_loss: float | None = Field(None, description="Calculated stop-loss price level")

    optimal_weights: dict[str, float] = Field(
        default_factory=dict,
        description=(
            "SLSQP-computed per-ticker recommended weights. "
            "Populated for multi-asset portfolio-level calls; empty for single-ticker calls."
        ),
    )
    optimizer_converged: bool | None = Field(
        None,
        description=(
            "Whether the SLSQP solve reported success. None when the solver was never "
            "invoked (single-asset call). False means optimal_weights is empty and no "
            "portfolio-level cap was applied."
        ),
    )

    api_calls_used: int = Field(0, ge=0)
    timestamp: datetime = Field(..., description="Naive local timestamp of signal production")

    @model_validator(mode="after")
    def approved_le_proposed(self) -> RiskAssessment:
        """Enforces that approved_weight never exceeds proposed_weight.

        Violated when an upstream bug or rounding error inflates the approved weight.
        A hard validation error is intentional to surface configuration issues early.
        """
        if self.approved_weight > self.proposed_weight + 1e-6:
            raise ValueError(
                f"approved_weight ({self.approved_weight}) cannot exceed "
                f"proposed_weight ({self.proposed_weight})"
            )
        return self


class AggregatedSignal(BaseModel):
    """Consolidated multi-agent directional stance and consensus conviction."""

    ticker: str = Field(..., description="Equity ticker symbol")
    signal: Signal = Field(..., description="Aggregated directional label")
    conviction: _Conviction = Field(..., description="Aggregated conviction score")
    weighted_votes: dict[str, float] = Field(
        ...,
        description=(
            "Agent name → weighted vote value used in aggregation. "
            "Keys include 'technical', 'fundamental', 'sentiment'. Consumed "
            "by orchestration/reconciliation.py's leave-one-out credit assignment."
        ),
    )
    agents_present: list[str] = Field(
        default_factory=list,
        description=(
            "Agent names that supplied a non-None signal into this aggregation. "
            "Distinguishes an agent that was absent from one that voted zero — "
            "weighted_votes alone cannot tell the two apart."
        ),
    )
    reliability: dict[str, float] = Field(
        default_factory=dict,
        description=(
            "Agent name → per-regime historical win rate used to scale that agent's "
            "vote weight at aggregation time (see HybridSignalAggregator.aggregate's "
            "reliability parameter). Persisted so orchestration/reconciliation.py's "
            "leave-one-out ablation can replay the same weighting the baseline used, "
            "instead of silently resetting every ablated rerun to the 1.0 unweighted default."
        ),
    )
    reliability_n: dict[str, int] = Field(
        default_factory=dict,
        description=(
            "Agent name → raw sample count each reliability rate was computed from "
            "(see cultural.get_agent_accuracy's n). Session-level, identical across "
            "every ticker's AggregatedSignal this run. Persisted so agents/portfolio.py's "
            "Half-Kelly anchor can tell '0.5 because no outcome data exists yet' from "
            "'0.5 because that is the measured win rate', without re-querying cultural "
            "memory per ticker."
        ),
    )
    model_healthy: bool = Field(
        True,
        description=(
            "False when reliability weighting fell back to the 0.5 neutral prior "
            "because cultural memory was unavailable (e.g. an ImportError on its "
            "optional [models] extra), rather than because no outcome history "
            "exists yet. Distinguishes a broken dependency from a genuinely new "
            "system — see reliability_n for the latter, which is 0 in both cases."
        ),
    )


class ProposedPosition(BaseModel):
    """A position as the LLM proposes it — advisory, not yet risk-enforced.

    Never carries allocation_usd or a risk-approved stop_loss: the agent computes
    the former from allocation_pct and overrides the latter with the risk engine's
    own figure when one exists. See GLOSSARY.md's Proposal entry.
    """

    ticker: Annotated[str, PromptText('""')] = Field(..., description="Equity ticker symbol")
    allocation_pct: Annotated[float, PromptText("0.0")] = Field(
        0.0, description="Proposed target portfolio weight"
    )
    stop_loss: Annotated[float | None, PromptText("0.0")] = Field(
        None, description="Model's own stop-loss estimate"
    )
    target_price: Annotated[float | None, PromptText("null")] = Field(
        None, description="12-month price target (optional)"
    )
    thesis: Annotated[str, PromptText('"<≤20 words>"')] = Field(
        ..., description="One-sentence position thesis"
    )
    advisor_note: Annotated[
        str | None,
        PromptText('"2–4 professional sentences: rationale, key risks, what to monitor"'),
    ] = Field(None, description="Professional multi-sentence advisory rationale (optional)")
    composite_conviction: Annotated[float, PromptText("0.0")] = Field(
        ..., ge=0.0, le=1.0, description="Aggregated conviction across all agents"
    )
    time_horizon: Annotated[str, PromptText('"3-6 months"')] = Field(
        ..., description="Expected holding period, e.g. '30 days'"
    )


class PortfolioProposal(BaseModel):
    """What the LLM itself returns for portfolio allocation — judgement only.

    Advisory until the risk engine has enforced against it: caps, vetoes, and the
    cash residual are all applied by the agent afterwards, never trusted from this
    object directly. See GLOSSARY.md's Proposal entry.
    """

    portfolio: list[ProposedPosition] = Field(default_factory=list)
    cash_reserve_pct: Annotated[float, PromptText("0.0")] = Field(
        ..., description="Model's own residual estimate"
    )
    rebalance_trigger: Annotated[str, PromptText('"MONTHLY"')] = Field(
        ..., description="Condition that will next trigger rebalancing, e.g. 'VIX > 35'"
    )


class PositionAllocation(BaseModel):
    """Target allocation weight, pricing levels, and thesis for one asset."""

    ticker: str = Field(..., description="Equity ticker symbol")
    allocation_pct: float = Field(
        ...,
        ge=0.0,
        le=SYSTEM.max_single_position_pct,
        description="Target portfolio weight [0, SYSTEM.max_single_position_pct]",
    )
    allocation_usd: float = Field(..., ge=0.0, description="Dollar value of the position")
    stop_loss: float = Field(..., description="Stop-loss price level")
    target_price: float | None = Field(None, description="12-month price target (optional)")
    thesis: str = Field(
        ..., max_length=120, description="One-sentence position thesis (≤120 chars)"
    )
    advisor_note: str | None = Field(
        None,
        max_length=600,
        description="Professional multi-sentence advisory rationale generated by the Portfolio Manager (≤600 chars)",
    )
    composite_conviction: float = Field(
        ..., ge=0.0, le=1.0, description="Aggregated conviction across all agents"
    )
    time_horizon: str = Field(..., description="Expected holding period, e.g. '30 days'")


class PortfolioAllocation(BaseModel):
    """Portfolio-level allocation of equity positions and cash reserves."""

    session_id: str = Field(..., description="Unique identifier for this advisory session")
    user_investable_capital: float = Field(
        ..., gt=0.0, description="Total wealth this allocation was computed against (USD) — "
        "the capital base for allocation_pct and allocation_usd, not wealth pre-scaled by invest_pct"
    )
    portfolio: list[PositionAllocation] = Field(
        default_factory=list, description="List of recommended positions"
    )
    cash_reserve_pct: float = Field(
        ...,
        ge=PORTFOLIO.cash_reserve_floor_pct,
        le=1.00,
        description="Fraction of capital held as cash [PORTFOLIO.cash_reserve_floor_pct, 1.00]",
    )
    rebalance_trigger: str = Field(
        ..., description="Condition that will next trigger rebalancing, e.g. 'VIX > 35'"
    )
    api_calls_used: int = Field(1, ge=0)
    timestamp: datetime = Field(..., description="Naive local timestamp of signal production")

    @field_validator("portfolio")
    @classmethod
    def tickers_are_unique(
        cls, portfolio: list[PositionAllocation]
    ) -> list[PositionAllocation]:
        """Rejects a portfolio with a repeated ticker.

        Every downstream consumer (node_log_decisions, risk cap enforcement)
        keys positions by ticker; a duplicate would silently overwrite one
        of the two allocations rather than raising.
        """
        counts = Counter(pos.ticker for pos in portfolio)
        duplicates = sorted(ticker for ticker, n in counts.items() if n > 1)
        if duplicates:
            raise ValueError(f"Duplicate ticker(s) in portfolio: {duplicates}")
        return portfolio

    @model_validator(mode="after")
    def total_allocation_sums_to_one(self) -> PortfolioAllocation:
        """Verifies that equity weights + cash_reserve_pct sum to 1.0 ± 0.05.

        The upper bound (> 1.01) prevents leverage by catching over-allocation.
        The lower bound (< 0.95) catches a silent under-deployment bug where the LLM
        sets a low cash_reserve_pct *and* a low equity allocation, leaving a large
        fraction of capital completely unaccounted for.

        cash_reserve_pct should always be treated as the residual:
            cash_reserve_pct = 1.0 - sum(allocation_pct)
        """
        total_equity = sum(p.allocation_pct for p in self.portfolio)
        grand_total = total_equity + self.cash_reserve_pct
        if grand_total > 1.01:
            raise ValueError(
                f"Over-allocated: equity ({total_equity:.4f}) + cash "
                f"({self.cash_reserve_pct:.4f}) = {grand_total:.4f} > 1.01. "
                "Reduce position sizes or lower the cash reserve."
            )
        if grand_total < 0.95:
            raise ValueError(
                f"Under-allocated: equity ({total_equity:.4f}) + cash "
                f"({self.cash_reserve_pct:.4f}) = {grand_total:.4f} < 0.95. "
                "Set cash_reserve_pct = 1.0 - sum(allocation_pct) so all "
                "capital is accounted for."
            )
        return self


class ARGUSDecision(BaseModel):
    """Unified snapshot of agent signals, risk limits, and target weights."""

    decision_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="UUID v4 unique identifier for this decision record",
    )
    ticker: str = Field(..., description="Equity ticker symbol")
    session_timestamp: datetime = Field(..., description="Naive local timestamp of the decision cycle")

    # All signal fields are optional; populated as each agent completes
    technical: TechnicalSignal | None = Field(None)
    macro: MacroContext | None = Field(None)
    fundamental: FundamentalSignal | None = Field(None)
    sentiment: SentimentSignal | None = Field(None)
    risk: RiskAssessment | None = Field(None)
    aggregated: AggregatedSignal | None = Field(None)
    allocation: PositionAllocation | None = Field(None)

    image_tag: str | None = Field(
        None,
        description=(
            "Commit-identified image tag of the build that produced this decision "
            "(argus.config.settings.ARGUS_IMAGE_TAG); stamped by append_decisions_jsonl, "
            "None until then"
        ),
    )

    @computed_field  # type: ignore[misc]
    @property
    def total_api_calls(self) -> int:
        """Total api_calls_used summed across every non-None child schema."""
        sources = [self.technical, self.macro, self.fundamental, self.sentiment, self.risk]
        return sum(s.api_calls_used for s in sources if s is not None)


__all__ = [
    "Signal",
    "Regime",
    "RiskVerdict",
    "VixRegime",
    "YieldCurve",
    "SectorSignal",
    "SESSION_STATE_REQUIRED_KEYS",
    "missing_session_state_keys",
    "MacroContext",
    "TechnicalSignal",
    "FundamentalVerdict",
    "FundamentalSignal",
    "SentimentVerdict",
    "SentimentSignal",
    "RiskAssessment",
    "AggregatedSignal",
    "ProposedPosition",
    "PortfolioProposal",
    "PositionAllocation",
    "PortfolioAllocation",
    "ARGUSDecision",
]
